name: New functional requirement
description: New functional requirement
title: "[FR-xx] <title>"
labels: ["functional", "product-backlog", "feature"]
body:
- type: input
  attributes:
    label: Goal
    description: The primary objective of this feature
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: A concise description of  the proposed feature
  validations:
    required: true
- type: input
  attributes:
    label: Stakeholders
    description: Group of users who will use this feature.
  validations:
    required: true
- type: input
  attributes:
    label: Date
    description: Last modified date
  validations:
    required: false
- type: input
  attributes:
    label: Version
    description: requirement version
  validations:
    required: false
- type: input
  attributes:
    label: Origin
    description: |
      examples:
        - Project description document
        - Group meeting
- type: dropdown
  attributes:
    label: Priority of the proposed feature    
    options:
      - Must have
      - Should have
      - Could have
      - Won't have
