name: New functional requirement
description: New functional requrement
title: "[FR] <title>"
labels: ["functional", "product-backlog", "feature"]
body:
- type: input
  attributes:
    label: Title
    description: A short title to refer to this feature
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: A concise description of  the proposed feature
  validations:
    required: true
- type: input
  attributes:
    label: Stakeholders
    description: Group of users, who will use this feature.
    placeholder: |
      1. Students
      2. Instructors      
  validations:
    required: true
- type: input
  attributes:
    label: Origin
    description: |
      examples:
        - Project desciption document
        - Group meeting
