name: New non-functional requirement
description: New functional requrement
title: "[NFR] <title>"
labels: ["non-functional", "product-backlog", "constraints"]
body:
- type: input
  attributes:
    label: Title
    description: A short title to refer to this non-functional requirement
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: A concise description of  the proposed constraints
  validations:
    required: true
- type: input
  attributes:
    label: Stakeholders
    description: Group of users, who are affected.
  validations:
    required: true
- type: input
  attributes:
    label: Date
    description: Last modified date
  validations:
    required: false
- type: input
  attributes:
    label: Origin
    description: |
      examples:
        - Project desciption document
        - Group meeting
- type: dropdown
  attributes:
    label: Priority of the proposed feature    
    options:
      - Must have
      - Should have
      - Could have
      - Won't have
